public static class PromptConstant
{
    public static readonly string NOTICE = "Notice";
    public static readonly string ERROR = "Error";
    public static readonly string EXIT = "Exit";
    public static readonly string YES = "Yes";
    public static readonly string YES_PROCEED = "Yes, please proceed";
    public static readonly string NO = "No";
    public static readonly string EXIT_PROMPT = "Are you sure to exit?";
    public static readonly string PLACE_ORDER_PROMPT = "Are you sure to place this order?";
    public static readonly string PLACE_THROTTLE_ORDER_PROMPT = "Are you sure to place this throttle/break even order?";
    public static readonly string CANCEL_ORDER_PROMPT = "Are you sure to cancel this order?";
    public static readonly string CANCEL_THROTTLE_ORDER_PROMPT = "Are you sure to cancel this throttle/break even order?";
    public static readonly string CLOSE_POSITION_PROMPT = "This action will exit the current position with market rate and it is irreversible, are you sure?";
    public static readonly string CLOSE_THROTTLE_POSITION_PROMPT = "This action will exit throttle position with market rate and it is irreversible/cancel the break even order, are you sure?";
    public static readonly string UNABLE_TO_CONTINUE_LOGIN = "Unable to continue previous login session, please re-login.";
    public static readonly string PASSWORD_MISMATCH = "Password does not matched with confirm password.";
    public static readonly string LOGIN = "Login";
    public static readonly string LOGOUT = "Logout";
    public static readonly string LOGOUT_CONFIRM = "Are you sure to log out now?";
    public static readonly string REGISTER = "Register";
    public static readonly string SWITCH_TO_REGISTER = "Dont' have account? Click here to register";
    public static readonly string SWITCH_TO_LOGIN = "Already have account? Click here to login";
    public static readonly string CONNECTED = "Connected";
    public static readonly string EMAIL_EMPTY = "Email can't be empty.";
    public static readonly string EMAIL_INVALID = "Email format invalid.";
    public static readonly string PASSWORD_EMPTY = "Password can't be empty.";
    public static readonly string API_KEY_EMPTY = "Api key/secret can't be empty.";
    public static readonly string PROFILE_NAME_EMPTY = "Profile name can't be empty.";
    public static readonly string REMOVE_PROFILE = "Remove Profile";
    public static readonly string REMOVE_PROFILE_CONFIRM = "Are you sure to remove current profile named ";
    public static readonly string DISCONNECT_PLATFORM = "Disconnect Platform";
    public static readonly string DISCONNECT_PLATFORM_CONFIRM = "Are you sure to disconnect/unlink this platform from your account?";
    public static readonly string NOT_AUTHORIZED = "Not authorized.";
    public static readonly string SWITCH_PLATFORM = "Switch Platform";
    public static readonly string SWITCH_PLATFORM_CONFIRM = "This action will delete all the orders(including on going positions)/quick orders/bots under this profile, are you sure to continue?";
    public static readonly string SWITCH_PLATFORM_CANCELLED = "Switch Platform Cancelled";
    public static readonly string DATA_FETCHED = "Data Fetched";
}