public enum WebsocketEventTypeEnum
{
    CONNECTION_ESTABLISH, // From Server

    #region Two Way
    VERSION_CHECKING,
    CREATE_ACCOUNT,
    GET_JWT,
    REVOKE_JWT,
    ADD_PLATFORM,
    REMOVE_PLATFORM,
    ADD_PROFILE,
    REMOVE_PROFILE,
    UPDATE_PROFILE,
    GET_PROFILE_DATA,
    GET_INITIAL_DATA,
    CALL_API,
    ADD_ORDER,
    UPDATE_ORDER,
    DELETE_ORDER,
    SUBMIT_ORDER,
    ADD_THROTTLE_ORDER,
    UPDATE_THROTTLE_ORDER,
    DELETE_THROTTLE_ORDER,
    SUBMIT_THROTTLE_ORDER,
    GET_RUNTIME_DATA,
    ADD_QUICK_ORDER,
    DELETE_QUICK_ORDER,
    ADD_TRADING_BOT,
    DELETE_TRADING_BOT,
    GET_BALANCE,
    GET_EXCHANGE_INFO,
    GET_FEE,
    #endregion

    #region From Server
    POSITION_INFO_UPDATE,
    SPAWN_ORDER,
    #endregion
}